bot:
  token: ODg4NDc0NzI1NDE4OTU0Nzky.G9W70w.uEouGtQdnmkYdQL4B54jrwOD_54QIrNSwZoC1E
  database:
    url: jdbc:postgresql://localhost:5432/casino_db?serverTimezone=UTC
    username: postgres
    password: Coffee4Sip
    use-ddl: true

code:
  package: com.eleven.casinobot
